INSERT INTO ejercicios (nombre, musculo_principal, musculos_secundarios, categoria, equipo, nivel, instrucciones, consejos) VALUES
('Press banca plano barra', 'Pectoral mayor', '{"Triceps", "Hombro"}', 'Pecho', 'Barra', 'intermedio', 'Baja la barra al pecho y empuja arriba', 'Omoplatos retraidos y pies en el suelo'),
('Press banca inclinado barra', 'Pectoral superior', '{"Triceps", "Hombro"}', 'Pecho', 'Barra', 'intermedio', 'Banco 45 grados, baja barra al pecho alto', 'Enfoca la contraccion en el pecho alto'),
('Press banca declinado barra', 'Pectoral inferior', '{"Triceps"}', 'Pecho', 'Barra', 'intermedio', 'Banco declinado, baja barra al pecho bajo', 'Cuidado al descolgar la barra'),
('Press inclinado mancuernas', 'Pectoral superior', '{"Triceps"}', 'Pecho', 'Mancuernas', 'principiante', 'Baja mancuernas y empuja arriba en banco inclinado', 'Gira munecas al subir para mayor contraccion'),
('Press plano mancuernas', 'Pectoral mayor', '{"Triceps"}', 'Pecho', 'Mancuernas', 'principiante', 'Baja mancuernas a los lados del pecho y empuja', 'Manten los codos a 45 grados del torso'),
('Aperturas con mancuernas', 'Pectoral mayor', '{"Hombro"}', 'Pecho', 'Mancuernas', 'principiante', 'Abre y cierra brazos en arco sobre el banco', 'Codo ligeramente flexionado todo el tiempo'),
('Aperturas inclinadas mancuernas', 'Pectoral superior', '{"Hombro"}', 'Pecho', 'Mancuernas', 'principiante', 'Abre y cierra en arco en banco inclinado', 'Siente el estiramiento del pecho al abrir'),
('Fondos en paralelas pecho', 'Pectoral inferior', '{"Triceps"}', 'Pecho', 'Peso corporal', 'intermedio', 'Torso inclinado, baja y sube empujando', 'Mas inclinacion al frente, mas trabaja el pecho'),
('Crossover polea alta', 'Pectoral mayor', '{"Hombro"}', 'Pecho', 'Polea', 'principiante', 'Desde arriba, une las manos al centro abajo', 'Manten codos ligeramente flexionados'),
('Crossover polea baja', 'Pectoral inferior', '{"Hombro"}', 'Pecho', 'Polea', 'principiante', 'Desde abajo, une las manos al centro arriba', 'Aprieta el pecho al juntar las manos'),
('Pullover con mancuerna', 'Pectoral mayor', '{"Dorsal"}', 'Pecho', 'Mancuerna', 'intermedio', 'Baja mancuerna detras de la cabeza y regresa', 'Manten codos ligeramente flexionados'),
('Pec deck mariposa', 'Pectoral mayor', '{"Hombro"}', 'Pecho', 'Maquina', 'principiante', 'Cierra los brazos al frente en la maquina', 'Aprieta el pecho al juntar los brazos'),
('Press en maquina pecho', 'Pectoral mayor', '{"Triceps"}', 'Pecho', 'Maquina', 'principiante', 'Empuja los handles al frente y regresa lento', 'Ajusta el asiento a la altura del pecho'),
('Push up clasico', 'Pectoral mayor', '{"Triceps", "Core"}', 'Pecho', 'Peso corporal', 'principiante', 'Baja el pecho al suelo y empuja arriba', 'Cuerpo en linea recta de cabeza a pies'),
('Push up inclinado', 'Pectoral superior', '{"Triceps"}', 'Pecho', 'Peso corporal', 'principiante', 'Pies elevados en banco, baja y empuja arriba', 'Mas elevados los pies, mas trabaja el pecho alto'),
('Dominadas agarre prono', 'Dorsal ancho', '{"Biceps", "Romboides"}', 'Espalda', 'Peso corporal', 'intermedio', 'Sube hasta que la barbilla pase la barra', 'Sin impulso de piernas al subir'),
('Dominadas agarre supino', 'Dorsal ancho', '{"Biceps"}', 'Espalda', 'Peso corporal', 'intermedio', 'Agarre supino, sube hasta la barra y baja', 'Activa mas el biceps que el agarre prono'),
('Dominadas agarre cerrado', 'Dorsal ancho', '{"Biceps"}', 'Espalda', 'Peso corporal', 'avanzado', 'Manos juntas, sube controlado y baja lento', 'Mas dificil que el agarre ancho'),
('Jalon al pecho agarre ancho', 'Dorsal ancho', '{"Biceps", "Romboides"}', 'Espalda', 'Polea', 'principiante', 'Jala la barra al pecho y regresa con control', 'Torso ligeramente inclinado hacia atras'),
('Jalon al pecho agarre cerrado', 'Dorsal ancho', '{"Biceps"}', 'Espalda', 'Polea', 'principiante', 'Jala barra triangular al pecho y regresa', 'Aprieta el dorsal al llegar abajo'),
('Jalon al pecho agarre supino', 'Dorsal ancho', '{"Biceps"}', 'Espalda', 'Polea', 'principiante', 'Agarre supino, jala al pecho y regresa lento', 'Activa mas el biceps que el agarre prono'),
('Remo con barra', 'Dorsal ancho', '{"Romboides", "Biceps"}', 'Espalda', 'Barra', 'intermedio', 'Torso 45 grados, tira la barra al abdomen', 'Espalda recta, nunca la redondees'),
('Remo con mancuerna', 'Dorsal ancho', '{"Romboides", "Biceps"}', 'Espalda', 'Mancuerna', 'principiante', 'Rodilla en banco, tira la mancuerna hacia cadera', 'Lleva el codo bien atras al subir'),
('Remo en polea sentado', 'Dorsal ancho', '{"Romboides", "Biceps"}', 'Espalda', 'Polea', 'principiante', 'Sentado, tira la barra al abdomen y regresa', 'Espalda erguida, no te eches atras'),
('Remo en T', 'Dorsal ancho', '{"Romboides", "Biceps"}', 'Espalda', 'Barra', 'intermedio', 'Pecho apoyado, tira la barra hacia arriba', 'Aprieta los omoplatos arriba del movimiento'),
('Peso muerto convencional', 'Isquiotibiales', '{"Gluteos", "Erectores"}', 'Espalda', 'Barra', 'avanzado', 'Levanta la barra del suelo extendiendo caderas', 'La barra debe rozar las piernas siempre'),
('Encogimientos con barra', 'Trapecios', '{"Romboides"}', 'Espalda', 'Barra', 'principiante', 'Sube los hombros hacia las orejas y baja', 'Brazos rectos, sin girar los hombros'),
('Encogimientos con mancuernas', 'Trapecios', '{"Romboides"}', 'Espalda', 'Mancuernas', 'principiante', 'Sube hombros a las orejas con mancuernas', 'Aguanta la contraccion 1 segundo arriba'),
('Face pull espalda', 'Deltoides posterior', '{"Romboides"}', 'Espalda', 'Polea', 'principiante', 'Jala la cuerda hacia la cara con codos altos', 'Codos altos y abiertos al llegar a la cara'),
('Pullover en polea dorsal', 'Dorsal ancho', '{"Pectoral"}', 'Espalda', 'Polea', 'principiante', 'Tira la barra desde arriba hasta las caderas', 'Manten los brazos rectos en todo momento'),
('Press militar con barra', 'Deltoides anterior', '{"Deltoides medio", "Triceps"}', 'Hombros', 'Barra', 'intermedio', 'De pie, empuja la barra sobre la cabeza', 'Contrae el core para proteger la lumbar'),
('Press militar con mancuernas', 'Deltoides anterior', '{"Deltoides medio", "Triceps"}', 'Hombros', 'Mancuernas', 'principiante', 'Sentado, empuja mancuernas arriba y baja', 'Espalda apoyada en el respaldo del banco'),
('Arnold press', 'Deltoides anterior', '{"Deltoides medio"}', 'Hombros', 'Mancuernas', 'intermedio', 'Gira las palmas al empujar las mancuernas arriba', 'Activa todas las cabezas del deltoides'),
('Elevaciones laterales mancuernas', 'Deltoides medio', '{"Trapecios"}', 'Hombros', 'Mancuernas', 'principiante', 'Sube brazos al lado hasta la altura del hombro', 'Inclina el pulgar hacia abajo al subir'),
('Elevaciones laterales polea', 'Deltoides medio', '{"Trapecios"}', 'Hombros', 'Polea', 'principiante', 'Sube el brazo lateralmente desde polea baja', 'El cable mantiene tension constante'),
('Elevaciones frontales mancuernas', 'Deltoides anterior', '{"Trapecios"}', 'Hombros', 'Mancuernas', 'principiante', 'Sube un brazo al frente alternando hasta hombros', 'Codo ligeramente flexionado al subir'),
('Elevaciones frontales barra', 'Deltoides anterior', '{"Trapecios"}', 'Hombros', 'Barra', 'principiante', 'Sube la barra al frente hasta los hombros', 'Manten codos ligeramente doblados'),
('Pajaros con mancuernas', 'Deltoides posterior', '{"Romboides"}', 'Hombros', 'Mancuernas', 'principiante', 'Torso inclinado, abre los brazos hacia atras', 'Junta los omoplatos al subir'),
('Pajaros en maquina', 'Deltoides posterior', '{"Romboides"}', 'Hombros', 'Maquina', 'principiante', 'Pecho apoyado, abre brazos atras y regresa', 'Mantén una leve flexion de codo'),
('Face pull hombros', 'Deltoides posterior', '{"Manguito rotador"}', 'Hombros', 'Polea', 'principiante', 'Jala cuerda hacia la cara con codos altos', 'Excelente para la salud del hombro'),
('Upright row barra', 'Deltoides medio', '{"Trapecios"}', 'Hombros', 'Barra', 'intermedio', 'Jala la barra al menton con codos hacia arriba', 'Barra cerca del cuerpo en todo momento'),
('Upright row mancuernas', 'Deltoides medio', '{"Trapecios"}', 'Hombros', 'Mancuernas', 'principiante', 'Jala mancuernas al menton con codos altos', 'No subas demasiado para cuidar el hombro'),
('Rotacion externa polea', 'Manguito rotador', '{"Deltoides posterior"}', 'Hombros', 'Polea', 'principiante', 'Codo a 90 grados, gira el brazo hacia afuera', 'Poco peso y movimiento muy controlado'),
('Curl barra recta', 'Biceps braquial', '{"Braquial"}', 'Brazos', 'Barra', 'principiante', 'Flexiona los codos subiendo la barra al pecho', 'Codos pegados al cuerpo todo el tiempo'),
('Curl barra EZ', 'Biceps braquial', '{"Braquial"}', 'Brazos', 'Barra EZ', 'principiante', 'Flexiona los codos con agarre en barra Z', 'Reduce tension en las munecas'),
('Curl mancuerna alterno', 'Biceps braquial', '{"Braquial"}', 'Brazos', 'Mancuernas', 'principiante', 'Sube una mancuerna a la vez flexionando', 'Supina la mano al subir para mas activacion'),
('Curl mancuerna simultaneo', 'Biceps braquial', '{"Braquial"}', 'Brazos', 'Mancuernas', 'principiante', 'Sube ambas mancuernas a la vez', 'Codos fijos a los costados del cuerpo'),
('Curl martillo', 'Braquial', '{"Biceps"}', 'Brazos', 'Mancuernas', 'principiante', 'Sube con agarre neutro tipo martillo', 'Trabaja mas el braquial y el antebrazo'),
('Curl concentrado', 'Biceps braquial', '{"Braquial"}', 'Brazos', 'Mancuerna', 'principiante', 'Codo en rodilla, sube la mancuerna contrayendo', 'Aislamiento total del biceps'),
('Curl en polea baja', 'Biceps braquial', '{"Braquial"}', 'Brazos', 'Polea', 'principiante', 'Flexiona el codo jalando la polea hacia hombro', 'Tension constante en el biceps'),
('Curl predicador', 'Biceps braquial', '{"Braquial"}', 'Brazos', 'Barra EZ', 'intermedio', 'Codo en banco predicador, sube y baja lento', 'Elimina el impulso del cuerpo'),
('Curl inclinado banco', 'Biceps braquial', '{"Braquial largo"}', 'Brazos', 'Mancuernas', 'intermedio', 'Banco inclinado, sube mancuernas con codos atras', 'Estira la cabeza larga del biceps'),
('Curl invertido', 'Braquiorradial', '{"Biceps"}', 'Brazos', 'Barra', 'intermedio', 'Agarre prono, flexiona los codos subiendo la barra', 'Fortalece antebrazos y munecas'),
('Press cerrado en banca', 'Triceps braquial', '{"Pectoral"}', 'Brazos', 'Barra', 'intermedio', 'Agarre cerrado, baja barra al pecho y empuja', 'Codos cerca del cuerpo al bajar'),
('Fondos en paralelas triceps', 'Triceps braquial', '{"Pectoral inferior"}', 'Brazos', 'Peso corporal', 'intermedio', 'Torso vertical, baja y sube manteniendo codos juntos', 'Mas vertical el torso, mas trabaja el triceps'),
('Extension polea alta', 'Triceps braquial', '{"Anconeo"}', 'Brazos', 'Polea', 'principiante', 'Empuja el cable hacia abajo extendiendo los codos', 'Codos fijos a los costados del cuerpo'),
('Extension polea baja', 'Triceps braquial', '{"Anconeo"}', 'Brazos', 'Polea', 'principiante', 'Desde polea baja, empuja hacia arriba extendiendo', 'Trabaja la cabeza larga del triceps'),
('Skull crusher', 'Triceps braquial', '{"Anconeo"}', 'Brazos', 'Barra EZ', 'intermedio', 'Acostado, baja la barra a la frente y extiende', 'Codos apuntando al techo siempre'),
('Extension sobre cabeza mancuerna', 'Triceps braquial', '{"Anconeo"}', 'Brazos', 'Mancuerna', 'principiante', 'Sosten mancuerna sobre la cabeza, baja y extiende', 'Estira bien la cabeza larga del triceps'),
('Extension sobre cabeza polea', 'Triceps braquial', '{"Anconeo"}', 'Brazos', 'Polea', 'principiante', 'De espaldas a la polea, extiende los brazos', 'Manten codos cerca de la cabeza'),
('Patada de triceps', 'Triceps braquial', '{"Anconeo"}', 'Brazos', 'Mancuerna', 'principiante', 'Torso inclinado, extiende el brazo hacia atras', 'Solo mueve el antebrazo, codo fijo'),
('Dips en banco', 'Triceps braquial', '{"Hombro"}', 'Brazos', 'Peso corporal', 'principiante', 'Manos en banco detras, baja el cuerpo y sube', 'Codos apuntando hacia atras al bajar'),
('Extension cuerda polea', 'Triceps braquial', '{"Anconeo"}', 'Brazos', 'Polea', 'principiante', 'Empuja la cuerda abajo y abre las manos al final', 'Abre las manos en la parte baja del movimiento'),
('Sentadilla con barra', 'Cuadriceps', '{"Gluteos", "Isquiotibiales"}', 'Piernas', 'Barra', 'intermedio', 'Barra en trapecios, baja hasta paralelo y sube', 'Rodillas alineadas con los pies al bajar'),
('Sentadilla goblet', 'Cuadriceps', '{"Gluteos"}', 'Piernas', 'Mancuerna', 'principiante', 'Mancuerna al pecho, baja en sentadilla profunda', 'Ideal para aprender la mecanica correcta'),
('Sentadilla sumo', 'Gluteos', '{"Cuadriceps", "Aductores"}', 'Piernas', 'Barra', 'intermedio', 'Pies abiertos y puntas afuera, baja y sube', 'Activa mas gluteos y aductores que la clasica'),
('Sentadilla bulgara', 'Cuadriceps', '{"Gluteos"}', 'Piernas', 'Mancuernas', 'intermedio', 'Pie atras en banco, baja en zancada y sube', 'Trabaja cada pierna de forma individual'),
('Hack squat', 'Cuadriceps', '{"Gluteos"}', 'Piernas', 'Maquina', 'intermedio', 'En maquina, baja hasta 90 grados y empuja', 'Pies altos trabajan mas gluteos'),
('Prensa 45 grados', 'Cuadriceps', '{"Gluteos", "Isquiotibiales"}', 'Piernas', 'Maquina', 'principiante', 'Baja la prensa a 90 grados de rodilla y empuja', 'La posicion de pies cambia el musculo'),
('Leg extension', 'Cuadriceps', '{"Recto femoral"}', 'Piernas', 'Maquina', 'principiante', 'Sentado, extiende las rodillas hacia arriba', 'Aislamiento puro del cuadriceps'),
('Leg curl tumbado', 'Isquiotibiales', '{"Biceps femoral"}', 'Piernas', 'Maquina', 'principiante', 'Tumbado, flexiona las rodillas hacia atras', 'Caderas apoyadas en la maquina siempre'),
('Leg curl sentado', 'Isquiotibiales', '{"Biceps femoral"}', 'Piernas', 'Maquina', 'principiante', 'Sentado, flexiona las rodillas hacia abajo', 'Mayor rango de movimiento que tumbado'),
('Peso muerto rumano', 'Isquiotibiales', '{"Gluteos", "Erectores"}', 'Piernas', 'Barra', 'intermedio', 'Baja la barra por piernas hasta sentir estiramiento', 'Espalda recta y rodillas ligeramente flexionadas'),
('Peso muerto sumo', 'Isquiotibiales', '{"Gluteos", "Aductores"}', 'Piernas', 'Barra', 'avanzado', 'Pies muy abiertos, levanta la barra del suelo', 'El ancho de pies reduce el recorrido'),
('Hip thrust con barra', 'Gluteos', '{"Isquiotibiales"}', 'Piernas', 'Barra', 'intermedio', 'Hombros en banco, empuja caderas arriba con barra', 'Aprieta los gluteos arriba del movimiento'),
('Lunges con mancuernas', 'Cuadriceps', '{"Gluteos"}', 'Piernas', 'Mancuernas', 'principiante', 'Da un paso al frente, baja rodilla al suelo y regresa', 'Torso erguido durante todo el movimiento'),
('Zancadas caminando', 'Cuadriceps', '{"Gluteos"}', 'Piernas', 'Mancuernas', 'principiante', 'Camina dando zancadas largas alternando piernas', 'Paso largo activa mas el gluteo'),
('Step up en banco', 'Cuadriceps', '{"Gluteos"}', 'Piernas', 'Mancuernas', 'principiante', 'Sube a un banco con una pierna y baja con control', 'Core activo al subir y al bajar'),
('Puente de gluteo', 'Gluteos', '{"Isquiotibiales"}', 'Gluteos', 'Peso corporal', 'principiante', 'Tumbado, empuja caderas arriba y aprieta gluteos', 'Aguanta la contraccion 2 segundos arriba'),
('Hip thrust con mancuerna', 'Gluteos', '{"Isquiotibiales"}', 'Gluteos', 'Mancuerna', 'principiante', 'Mancuerna en caderas, hombros en banco, empuja', 'Aprieta los gluteos al maximo arriba'),
('Patada trasera en polea', 'Gluteos', '{"Isquiotibiales"}', 'Gluteos', 'Polea', 'principiante', 'Lleva la pierna hacia atras con polea en tobillo', 'Torso estable, no arquees la espalda'),
('Abduccion en maquina', 'Gluteo medio', '{"Piriforme"}', 'Gluteos', 'Maquina', 'principiante', 'Sentado, empuja las rodillas hacia afuera y regresa', 'Aisla bien el gluteo medio'),
('Abduccion con banda', 'Gluteo medio', '{"Piriforme"}', 'Gluteos', 'Banda elastica', 'principiante', 'Con banda en rodillas, abre las piernas y regresa', 'Ideal para activar en calentamiento'),
('Sentadilla sumo con mancuerna', 'Gluteos', '{"Aductores"}', 'Gluteos', 'Mancuerna', 'principiante', 'Pies muy abiertos, baja con mancuerna al centro', 'Maximiza la activacion del gluteo'),
('Kickback en cuadrupedia', 'Gluteos', '{"Isquiotibiales"}', 'Gluteos', 'Peso corporal', 'principiante', 'En 4 apoyos, lleva una pierna atras y arriba', 'Core activo para no arquear la espalda'),
('Zancada lateral', 'Gluteo medio', '{"Aductores"}', 'Gluteos', 'Peso corporal', 'principiante', 'Paso lateral, baja sobre esa pierna y regresa', 'Pie completo apoyado al bajar'),
('Plancha frontal', 'Transverso abdominal', '{"Oblicuos", "Core"}', 'Core', 'Peso corporal', 'principiante', 'Apoyado en antebrazos, cuerpo recto y firme', 'No dejes caer ni elevar las caderas'),
('Plancha lateral', 'Oblicuos', '{"Transverso"}', 'Core', 'Peso corporal', 'principiante', 'Apoyado en un antebrazo y pie, cadera arriba', 'Cuerpo en linea recta de cabeza a pies'),
('Crunch abdominal', 'Recto abdominal', '{"Oblicuos"}', 'Core', 'Peso corporal', 'principiante', 'Eleva los hombros contrayendo el abdomen', 'No tires del cuello con las manos'),
('Crunch inverso', 'Recto abdominal', '{"Oblicuos"}', 'Core', 'Peso corporal', 'principiante', 'Lleva las rodillas al pecho contrayendo el abdomen', 'Controla la bajada de piernas'),
('Elevacion de piernas tumbado', 'Recto abdominal inferior', '{"Flexores de cadera"}', 'Core', 'Peso corporal', 'intermedio', 'Sube piernas rectas hasta 90 grados y baja lento', 'Baja lento para mayor activacion'),
('Russian twist', 'Oblicuos', '{"Recto abdominal"}', 'Core', 'Peso corporal', 'principiante', 'Sentado, gira el torso de lado a lado', 'Sosten una mancuerna para mas intensidad'),
('Dead bug', 'Transverso abdominal', '{"Oblicuos"}', 'Core', 'Peso corporal', 'principiante', 'Extiende brazo y pierna contraria y regresa', 'Zona lumbar pegada al suelo siempre'),
('Mountain climbers', 'Recto abdominal', '{"Core", "Hombros"}', 'Core', 'Peso corporal', 'principiante', 'En plancha, alterna rodillas hacia el pecho rapido', 'Caderas bajas y core activo siempre'),
('Elevacion talon de pie', 'Gemelo', '{"Soleo"}', 'Pantorrillas', 'Peso corporal', 'principiante', 'Sube sobre las puntas de los pies y baja lento', 'Pausa arriba apretando el gemelo'),
('Elevacion talon sentado', 'Soleo', '{"Gemelo"}', 'Pantorrillas', 'Maquina', 'principiante', 'Peso en rodillas, sube sobre las puntas y baja', 'El soleo trabaja mejor con rodilla flexionada'),
('Elevacion talon en prensa', 'Gemelo', '{"Soleo"}', 'Pantorrillas', 'Maquina', 'principiante', 'Pies en borde de prensa, sube y baja las puntas', 'Mayor rango de movimiento que de pie'),
('Elevacion talon unilateral', 'Gemelo', '{"Soleo"}', 'Pantorrillas', 'Peso corporal', 'intermedio', 'Una pierna a la vez, sube y baja la punta', 'Mas intenso que la version con dos piernas'),
('Elevacion talon con barra', 'Gemelo', '{"Soleo"}', 'Pantorrillas', 'Barra', 'intermedio', 'Barra en hombros, sube sobre las puntas y baja', 'Usa plataforma para mayor rango de movimiento'),
('Donkey calf raise', 'Gemelo', '{"Soleo"}', 'Pantorrillas', 'Peso corporal', 'intermedio', 'Inclinado con peso en caderas, sube y baja puntillas', 'Estira el gemelo al maximo en la parte baja');
